on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '42 8 * * *'

permissions: write-all

jobs:
  check-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: '1.22.x'
      - name: Get latest release
        shell: bash
        run: ./check-for-new-release.sh "${{ secrets.GIT_TOKEN }}"
